#!/usr/bin/env bash
set -euo pipefail
echo "[05] Build human-readable summaries + HTML index"

mkdir -p reports/html

# Friendly table summaries (non-blocking if Trivy finds issues)
# FS summary
trivy fs --severity MEDIUM,HIGH,CRITICAL --format table "${WORKSPACE:-.}" > reports/html/trivy-fs.txt || true

# Image summary (use the exact image we just built)
FULL_TAG="$(cat image_tag.txt)"
trivy image --severity MEDIUM,HIGH,CRITICAL --format table "${FULL_TAG}" > reports/html/trivy-image.txt || true

# Build a minimal HTML index that embeds the text reports
cat > reports/index.html <<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Security Reports</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
 body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:24px;line-height:1.4}
 pre{white-space:pre-wrap;background:#f6f8fa;border:1px solid #eaecef;border-radius:8px;padding:12px}
 h1{margin-top:0}
 .grid{display:grid;grid-template-columns:1fr;gap:20px}
 .card{padding:10px;border:1px solid #eaecef;border-radius:10px;background:#fff}
 .muted{color:#666}
 a{color:#0366d6;text-decoration:none}
</style>
</head>
<body>
  <h1>Security Reports</h1>
  <p class="muted">Generated by Jenkins after Trivy scans.</p>
  <div class="grid">
    <div class="card">
      <h2>Filesystem Scan (Trivy FS)</h2>
      <p><a href="html/trivy-fs.txt" target="_blank">Open as text</a></p>
      <pre>
$(sed 's/&/\&amp;/g; s/</\&lt;/g' reports/html/trivy-fs.txt 2>/dev/null || echo "No FS report found.")
      </pre>
    </div>
    <div class="card">
      <h2>Image Scan (Trivy Image)</h2>
      <p><a href="html/trivy-image.txt" target="_blank">Open as text</a></p>
      <pre>
$(sed 's/&/\&amp;/g; s/</\&lt;/g' reports/html/trivy-image.txt 2>/dev/null || echo "No Image report found.")
      </pre>
    </div>
  </div>
</body>
</html>
HTML
echo "[05] HTML index written to reports/index.html"
